config/routes.rb
Rails.application.routes.draw do
  resources :products do
    get "delete"
  end
  root 'products#index'

  get "*path" => redirect("/")
  post "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
require 'date'
class Product < ApplicationRecord
  validates :product_type, :name, :description, :presence => {:message => "empty value found"}
  validates :product_status, :price, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
  #validate :is_inward_date_valid

  def is_inward_date_valid
    errors.add(:inward_date, 'must be a valid date') if ((Date.parse(:inward_date) rescue ArgumentError) == ArgumentError)
  end

  def self.price_sum(type)
    Product.where(:product_type => type).sum(&:price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = ProductDecorator.decorate_collection(Product.all)
  end

  def show
    @product = ProductDecorator.new(Product.find(params[:id]))
  end

  def new
    type = params[:product_type]
    @product = ProductDecorator.new(Product.new(:product_type => type))
  end

  def create
    @products = ProductDecorator.decorate_collection(Product.all)
    @product = Product.create(product_params)
  end

  def edit
    @product = ProductDecorator.new(Product.find(params[:id]))
  end

  def update
    @products = ProductDecorator.decorate_collection(Product.all)
    @product = ProductDecorator.new(Product.find(params[:id]))
    
    @product.update_attributes(product_params)
  end

  def delete
    @product = ProductDecorator.new(Product.find(params[:product_id]))
  end

  def destroy
    @products = ProductDecorator.decorate_collection(Product.all)
    @product = ProductDecorator.new(Product.find(params[:id]))
    @product.destroy
  end

private
  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(:name, :price, :color, :product_status, :inward_date, :product_type, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageProduct</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Product</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @product.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Product", product_path(@product), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "Cancel", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/products/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@product.name}" %></h3>
</div>
<%= render "form" %>

app/views/products/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @product, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
	<%= f.hidden_field :product_type %>

        <div class="form-group">
          <%= f.label :name, class:"control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price, class: "control-label" %>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <% if @product.product_type == 'Pen' %>
          <div class="form-group">
            <%= f.label :color %>
            <%= f.text_field :color, id: :product_color %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :product_status %>
          <%= f.check_box :product_status, id: :product_product_status %>
        </div>

        <div class="form-group">
          <%= f.label :inward_date %>
          <%= f.text_field :inward_date, id: :product_inward_date, class: 'datepicker' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, id: :product_description %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $.fn.datepicker.defaults.format = "dd-mm-yyyy";
  $(document).ready(function(){
    $('.datepicker').datepicker({
      autoclose:true,
      format: "dd-mm-yyyy"
    });
  });
</script>

app/views/products/_index.html.erb
<% @products.each do |product| %>
  <tr class="active">
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.colour %></td>
    <td><%= product.is_available %></td>
    <td><%= product.inward_date %></td>
    <td><%= product.product_type %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Edit', edit_product_path(product), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to 'Delete', product_delete_path(product), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>
<tr>
  <td colspan="5">Total Pen Price: <%= Product.price_sum('Pen')%></td>
  <td colspan="4">Total Notebook Price: <%= Product.price_sum('Notebook')%></td>
</tr>

app/views/products/_new.html.erb
<div class="modal-header">
<h3>New Product</h3>
</div>
<%= render "form" %>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  $("#product-modal").modal("hide")
<% end %>

app/views/products/create.js.erb
<%= render "save" %>

app/views/products/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/products/destroy.js.erb
<%= render 'save' %>

app/views/products/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/products/index.html.erb
<div class="container" style='margin-top: 5%;'>
  <div class="well">
    <%= link_to 'New Pen', new_product_path(:product_type => "Pen"), remote: true, class: "btn btn-primary" %>
    <%= link_to 'New Notebook', new_product_path(:product_type => "Notebook"), remote: true, class: "btn btn-primary" %>
  </div>


  <p id="notice"><%= notice %></p>
  <div class="new-product"></div>
  
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Color</th>
        <th>Product status</th>
        <th>Inward date</th>
        <th>Product type</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody class="product-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="product-modal" class="modal fade"></div>

app/views/products/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/products/update.js.erb
<%= render "save" %>